name: TOMMY
version: "2.2.5"
slug: tommysense-homeassistant-addon
description: TOMMY (Home Assistant Add-on)
url: "https://github.com/tommy-sense/homeassistant-addon"
arch:
  - aarch64
  - amd64
image: tommysense/homeassistant-addon-{arch}
startup: application
boot: auto
hassio_role: default
hassio_api: true
host_network: true # Needed for mDNS discovery
apparmor: true
ingress: true
ingress_port: 0
panel_icon: mdi:wifi-arrow-left-right
init: false
map:
  - type: data
    read_only: False
options:
  ports:
    dashboard: 8089
    file_server_http: 8090
    file_server_https: 8091
    mqtt: 1886
    udp_relay: 8547
schema:
  ports:
    dashboard: port
    file_server_http: port
    file_server_https: port
    mqtt: port
    udp_relay: port
  license_key: "str?"
  machine_certificate: "str?"